baseURL = "https://ffplayout.github.io/"
languageCode = "en-us"
title = "ffplayout"
theme = "m10c"

canonifyurls = true

[pagination]
pagerSize = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Rust/ffmpeg based playout"
  brand = "ffplayout"
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

  author = "Jonathan Baecker"
  description = "Rust/ffmpeg based playout"
  avatar = "/img/logo.png"
  menu_item_separator = "<br />"
  favicon = "/favicon.ico"

  [[params.social]]
    icon = "github"
    name = "ffplayout"
    url = "https://github.com/ffplayout"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Frontend"
    weight = 4
    identifier = "frontend"
    url = "/frontend/"
  [[menu.main]]
    name = "Install"
    weight = 4
    identifier = "install"
    url = "/install/"
